twig:
  default_path: "%kernel.project_dir%/templates"

  globals:
    batman: "I'm Batman"
    front: "Vous êtes sur la partie front"
    admin: "Vous êtes sur la partie admin"
    gcategories: '@App\Globals\Categories'
    gproducts: '@App\Globals\Products'

when@test:
  twig:
    strict_variables: true
